version: '3'

services:
    hub:
        build: ./hub
        ports:
          - '8081:8081'
        container_name: hub

    evaluator:
        build: ./evaluator
        ports:
            - '8080:8080'
        depends_on:
          - hub
          - validator
        container_name: evaluator

    broken-evaluator:
        build: ./broken-evaluator
        ports:
            - '8082:8082'
        depends_on:
            - hub
            - validator
        container_name: broken-evaluator

    swagger:
        build: ./swagger
        ports:
            - '8090:8090'
        depends_on:
          - hub
          - evaluator
          - broken-evaluator
        container_name: swagger

    validator:
        build: ./validator
        ports:
            - '8181:8181'
        container_name: validator

