spring.main:
  banner-mode: 'off'

logging.level:
  root: INFO

spreadsheet:
  url-for-getting-the-task: 'https://www.wix.com/_serverless/hiring-task-spreadsheet-evaluator/sheets'
  email-for-result-submission: 'vladimir.sol.rojo@gmail.com'
