spring.main:
  banner-mode: 'off'

server:
  port: 8090

spreadsheet-evaluator:
  url-for-spreadsheet-evaluation-service: 'http://evaluator:8080/api/spreadsheet-evaluation'
  url-for-broken-evaluation-service: 'http://broken-evaluator:8082/api/spreadsheet-evaluation'